
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/vic778@master
        with:
          WAKATIME_API_KEY: bc3bf636-319a-4782-a79c-f10db0a44700
          USERNAME: descholar
          SHOW_TITLE: true
